# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20170410_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='', max_length=255),
        ),
    ]
