# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-11 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0004_auto_20170411_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdog',
            name='user',
        ),
        migrations.AddField(
            model_name='userdog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
