# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-15 20:01
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0006_auto_20170414_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large')], default='s', max_length=2),
        ),
    ]
