# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0007_auto_20170415_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='pugorugh.Dog'),
        ),
    ]
