# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0011_auto_20170418_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Buddy', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], default='b, y, a, s', max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m, f', max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large')], default='s, m, l, xl', max_length=2),
        ),
    ]
