# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-23 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0016_auto_20170423_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='Unknown gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Unknown name', max_length=255),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], default='Unknown size', max_length=2),
        ),
    ]
