# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0017_auto_20170423_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
    ]
