# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0018_dog_neutered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=''),
        ),
    ]
